In [1]:
import pandas as pd
import math 
import matplotlib.pyplot as plt
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('max_colwidth', -1)
pd.set_option('display.expand_frame_repr', False)

In [3]:
deliveries = pd.read_csv('Desktop\MAS\DATASET\MAS-ACA-Masterclass-main\MAS-ACA-Masterclass-main\CSV Files\deliveries_updated.csv')
matches = pd.read_csv('Desktop\MAS\DATASET\MAS-ACA-Masterclass-main\MAS-ACA-Masterclass-main\CSV Files\matches_updated_mens_ipl.csv')

In [4]:
df = deliveries.copy()
mdf = matches.copy()

In [5]:
df.head()

   matchId  inning  over_ball  over  ball         batting_team                 bowling_team    batsman non_striker    bowler  batsman_runs  extras  isWide  isNoBall  Byes  LegByes  Penalty dismissal_kind player_dismissed
0  1082591  1       0.1        0     1     Sunrisers Hyderabad  Royal Challengers Bangalore  DA Warner  S Dhawan    TS Mills  0             0      NaN     NaN       NaN   NaN      NaN       NaN            NaN
1  1082591  1       0.2        0     2     Sunrisers Hyderabad  Royal Challengers Bangalore  DA Warner  S Dhawan    TS Mills  0             0      NaN     NaN       NaN   NaN      NaN       NaN            NaN
2  1082591  1       0.3        0     3     Sunrisers Hyderabad  Royal Challengers Bangalore  DA Warner  S Dhawan    TS Mills  4             0      NaN     NaN       NaN   NaN      NaN       NaN            NaN
3  1082591  1       0.4        0     4     Sunrisers Hyderabad  Royal Challengers Bangalore  DA Warner  S Dhawan    TS Mills  0             0      NaN     NaN       NaN   NaN      NaN       NaN            NaN
4  1082591  1       0.5        0     5     Sunrisers Hyderabad  Royal Challengers Bangalore  DA Warner  S Dhawan    TS Mills  0             2       2.0    NaN       NaN   NaN      NaN       NaN            NaN

In [6]:
mdf.head(1)

  outcome                  event        date gender reserve_umpire                team1                  toss_winner   umpire2 match_referee season                        team2  winner_runs  balls_per_over player_of_match date1 neutralvenue                                      venue method toss_decision       city   tv_umpire date2               winner      umpire1  match_number eliminator  winner_wickets  matchId
0  NaN     Indian Premier League  2017-04-05  male   N Pandit       Sunrisers Hyderabad  Royal Challengers Bangalore  NJ Llong  J Srinath     2017   Royal Challengers Bangalore  35.0         6               Yuvraj Singh    NaN   NaN          Rajiv Gandhi International Stadium, Uppal  NaN    field         Hyderabad  A Deshmukh  NaN   Sunrisers Hyderabad  AY Dandekar  1.0           NaN       NaN              1082591

In [7]:
def ByInnings(df, current_innings):
    
   
    df = df[df.inning == current_innings]
    df.reset_index(inplace = True, drop = True)


    df['IsDot'] = df['batsman_runs'].apply(lambda x : 1 if x == 0 else 0)
    df['IsOne'] = df['batsman_runs'].apply(lambda x : 1 if x == 1 else 0)
    df['IsTwo'] = df['batsman_runs'].apply(lambda x : 1 if x == 2 else 0)
    df['IsThree'] = df['batsman_runs'].apply(lambda x : 1 if x == 3 else 0)
    df['IsFour'] = df['batsman_runs'].apply(lambda x : 1 if x == 4 else 0)
    df['IsSix'] = df['batsman_runs'].apply(lambda x : 1 if x == 6 else 0)
   
    runs = pd.DataFrame(df.groupby(['batsman'])['batsman_runs'].sum()).reset_index().rename(columns = {'batsman_runs': 'runs'})
    balls = pd.DataFrame(df.groupby(['batsman'])['matchId'].count()).reset_index().rename(columns = {'matchId': 'balls'})
    innings = pd.DataFrame(df.groupby(['batsman'])['matchId'].apply(lambda x: len(list(np.unique(x))))).reset_index().rename(columns ={'matchId':'innings'})
    dismissals = pd.DataFrame(df.groupby(['batsman'])['player_dismissed'].count().reset_index().rename(columns = {'player_dismissed':'dismissals'}))
    sixes = pd.DataFrame(df.groupby(['batsman'])['IsSix'].sum().reset_index().rename(columns = {'IsSix':'sixes'}))
    fours = pd.DataFrame(df.groupby(['batsman'])['IsFour'].sum().reset_index().rename(columns = {'IsFour':'fours'}))
    
    df = pd.merge(innings, runs, on = 'batsman').merge(balls, on ='batsman').merge(dismissals, on ='batsman').merge(fours, on ='batsman').merge(sixes, on ='batsman')
    df['RPI'] = df.apply(lambda x: (x['runs']/x['innings']), axis = 1)
    
    return df

In [8]:
ing1_df = ByInnings(df, 1)

In [23]:
ByInnings(df, 1)

                     batsman  innings  runs  balls  dismissals  fours  sixes        RPI
0    A Ashish Reddy           13       166   115    7           6      10     12.769231
1    A Chandila               2        4     7      1           0      0      2.000000
2    A Chopra                 5        51    72     4           7      0      10.200000
3    A Choudhary              1        15    12     0           1      0      15.000000
4    A Dananjaya              1        4     5      0           0      0      4.000000
5    A Flintoff               1        22    14     0           2      1      22.000000
6    A Kumble                 5        11    16     1           1      0      2.200000
7    A Mishra                 25       145   176    15          13     1      5.800000
8    A Mithun                 2        8     5      1           1      0      4.000000
9    A Mukund                 1        19    22     1           1      0      19.000000
10   A Nehra                  9        6     19     5           0      0      0.666667
11   A Nortje                 1        3     1      0           0      0      3.000000
12   A Singh                  2        1     4      1           0      0      0.500000
13   A Symonds                19       622   472    12          46     31     32.736842
14   A Uniyal                 1        4     6      0           0      0      4.000000
15   AA Bilakhia              3        29    41     3           2      0      9.666667
16   AA Chavan                2        8     9      0           1      0      4.000000
17   AA Jhunjhunwala          7        142   134    8           16     1      20.285714
18   AB Agarkar               11       117   98     5           10     3      10.636364
19   AB Dinda                 7        7     22     4           0      0      1.000000
20   AB McDonald              5        74    57     3           8      3      14.800000
21   AB de Villiers           88       3163  1997   66          254    159    35.943182
22   AC Blizzard              2        43    30     2           9      0      21.500000
23   AC Gilchrist             41       943   763    40          106    41     23.000000
24   AC Thomas                1        0     2      0           0      0      0.000000
25   AC Voges                 5        138   99     3           12     3      27.600000
26   AD Hales                 3        52    53     3           5      0      17.333333
27   AD Mascarenhas           5        44    47     4           3      0      8.800000
28   AD Mathews               25       410   325    17          30     16     16.400000
29   AD Nath                  6        66    68     6           5      2      11.000000
30   AD Russell               34       917   520    26          58     82     26.970588
31   AF Milne                 2        1     2      1           0      0      0.500000
32   AG Murtaza               1        2     5      0           0      0      2.000000
33   AG Paunikar              3        24    34     3           4      0      8.000000
34   AJ Finch                 46       1094  897    44          111    39     23.782609
35   AJ Turner                1        0     1      1           0      0      0.000000
36   AJ Tye                   7        38    40     4           2      2      5.428571
37   AK Markram               2        69    62     2           8      0      34.500000
38   AL Menaria               15       250   237    15          17     9      16.666667
39   AM Nayar                 23       357   308    19          27     12     15.521739
40   AM Rahane                71       2034  1673   66          220    42     28.647887
41   AN Ahmed                 1        4     2      1           1      0      4.000000
42   AN Ghosh                 1        7     7      1           1      0      7.000000
43   AP Dole                  1        4     4      1           1      0      4.000000
44   AP Majumdar              1        30    20     1           1      2      30.000000
45   AP Tare                  16       197   175    15          27     4      12.312500
46   AR Bawne                 1        12    12     0           1      0      12.000000
47   AR Patel                 42       481   413    28          25     21     11.452381
48   AS Rajpoot               3        7     16     2           1      0      2.333333
49   AS Raut                  8        79    74     6           5      4      9.875000
50   AS Yadav                 5        46    36     7           5      2      9.200000
51   AT Carey                 2        28    22     1           0      1      14.000000
52   AT Rayudu                81       1917  1470   64          151    81     23.666667
53   AUK Pathan               3        2     7      2           0      0      0.666667
54   Abdul Samad              7        100   76     5           5      6      14.285714
55   Abhishek Sharma          11       151   108    6           11     9      13.727273
56   Anirudh Singh            2        40    43     2           4      1      20.000000
57   Ankit Sharma             5        58    48     4           6      2      11.600000
58   Ankit Soni               3        7     9      2           0      1      2.333333
59   Anureet Singh            3        11    8      0           0      1      3.666667
60   Arshdeep Singh           2        2     3      0           0      0      1.000000
61   Avesh Khan               1        5     3      0           1      0      5.000000
62   Azhar Mahmood            12       236   180    11          23     9      19.666667
63   B Akhil                  5        31    28     3           3      1      6.200000
64   B Chipli                 13       158   140    9           16     4      12.153846
65   B Kumar                  23       90    90     12          9      1      3.913043
66   B Laughlin               1        1     3      0           0      0      1.000000
67   B Lee                    11       64    53     5           3      5      5.818182
68   B Sumanth                2        13    16     0           0      0      6.500000
69   BA Bhatt                 1        6     2      0           0      1      6.000000
70   BA Stokes                18       336   291    18          22     10     18.666667
71   BAW Mendis               1        1     1      0           0      0      1.000000
72   BB McCullum              59       1681  1328   58          163    81     28.491525
73   BB Samantray             6        110   102    4           11     2      18.333333
74   BB Sran                  3        2     3      0           0      0      0.666667
75   BCJ Cutting              11       145   88     7           10     12     13.181818
76   BE Hendricks             2        1     3      1           0      0      0.500000
77   BJ Haddin                1        18    11     1           2      1      18.000000
78   BJ Hodge                 32       654   568    24          56     17     20.437500
79   BJ Rohrer                3        91    69     2           12     1      30.333333
80   BMAJ Mendis              1        11    9      1           0      0      11.000000
81   BR Dunk                  1        15    14     1           2      0      15.000000
82   Basil Thampi             5        21    24     2           0      1      4.200000
83   Bipul Sharma             9        68    50     2           3      3      7.555556
84   C Madan                  1        15    21     1           3      0      15.000000
85   C Munro                  7        118   88     6           14     5      16.857143
86   C Sakariya               4        15    20     4           2      0      3.750000
87   C de Grandhomme          10       133   79     7           7      10     13.300000
88   CA Ingram                5        78    62     4           9      2      15.600000
89   CA Lynn                  19       619   471    19          61     28     32.578947
90   CA Pujara                12       208   214    11          31     2      17.333333
91   CH Gayle                 76       2873  1959   73          240    201    37.802632
92   CH Morris                23       283   200    17          24     12     12.304348
93   CJ Anderson              16       307   258    12          22     17     19.187500
94   CJ Ferguson              4        42    51     4           4      0      10.500000
95   CJ Jordan                5        43    41     4           1      3      8.600000
96   CJ McKay                 1        8     15     1           0      0      8.000000
97   CK Kapugedera            2        8     15     2           0      0      4.000000
98   CL White                 26       666   481    18          51     29     25.615385
99   CM Gautam                6        78    74     4           9      3      13.000000
100  CR Brathwaite            10       147   90     10          5      15     14.700000
101  CR Woakes                6        49    49     3           6      0      8.166667
102  CV Varun                 2        3     5      2           0      0      1.500000
103  D Kalyankrishna          1        3     8      1           0      0      3.000000
104  D Padikkal               18       551   477    18          61     12     30.611111
105  D Salunkhe               1        26    20     0           4      0      26.000000
106  D Wiese                  3        28    21     2           2      1      9.333333
107  D du Preez               1        10    13     1           0      0      10.000000
108  DA Miller                44       850   647    32          66     35     19.318182
109  DA Warner                75       2880  2129   70          266    109    38.400000
110  DB Das                   10       184   166    6           11     12     18.400000
111  DB Ravi Teja             15       227   184    10          23     4      15.133333
112  DE Bollinger             3        21    22     1           1      1      7.000000
113  DH Yagnik                12       138   104    6           19     2      11.500000
114  DJ Bravo                 52       829   623    35          68     34     15.942308
115  DJ Harris                2        66    59     1           6      4      33.000000
116  DJ Hooda                 34       454   334    24          22     28     13.352941
117  DJ Hussey                36       739   635    31          51     30     20.527778
118  DJ Jacobs                5        69    78     5           8      2      13.800000
119  DJ Malan                 1        26    26     1           1      1      26.000000
120  DJ Muthuswami            1        1     3      1           0      0      1.000000
121  DJ Thornely              3        38    48     3           2      2      12.666667
122  DJG Sammy                12       220   188    11          15     12     18.333333
123  DJM Short                5        67    71     5           8      1      13.400000
124  DL Chahar                2        2     7      1           0      0      1.000000
125  DL Vettori               7        59    59     4           5      0      8.428571
126  DNT Zoysa                1        1     2      1           0      0      1.000000
127  DPMD Jayawardene         35       760   660    30          83     18     21.714286
128  DR Martyn                1        19    26     2           1      0      19.000000
129  DR Sams                  1        3     2      0           0      0      3.000000
130  DR Smith                 46       1105  914    44          113    49     24.021739
131  DS Kulkarni              8        25    23     4           2      0      3.125000
132  DS Lehmann               1        1     2      1           0      0      1.000000
133  DT Christian             26       327   290    20          17     13     12.576923
134  DT Patil                 1        4     1      0           1      0      4.000000
135  DW Steyn                 17       91    69     11          9      2      5.352941
136  E Lewis                  15       429   312    15          44     24     28.600000
137  EJG Morgan               39       732   598    33          55     37     18.769231
138  ER Dwivedi               2        24    15     2           2      2      12.000000
139  F Behardien              1        5     5      1           1      0      5.000000
140  F du Plessis             46       1444  1126   39          126    51     31.391304
141  FA Allen                 1        6     11     1           0      0      6.000000
142  FH Edwards               2        4     5      1           0      0      2.000000
143  FY Fazal                 7        161   143    6           20     1      23.000000
144  G Gambhir                62       1757  1408   59          196    34     28.338710
145  GC Smith                 11       369   292    11          45     7      33.545455
146  GC Viljoen               2        3     6      1           0      0      1.500000
147  GD Phillips              1        4     13     1           0      0      4.000000
148  GH Vihari                11       105   131    9           9      0      9.545455
149  GHS Garton               1        0     1      1           0      0      0.000000
150  GJ Bailey                20       417   311    17          39     12     20.850000
151  GJ Maxwell               50       1103  764    45          78     69     22.060000
152  GR Napier                1        15    16     1           1      0      15.000000
153  Gurkeerat Singh          19       267   219    16          27     8      14.052632
154  H Klaasen                2        38    29     2           3      1      19.000000
155  HF Gurney                1        1     5      0           0      0      1.000000
156  HH Gibbs                 18       472   421    16          44     18     26.222222
157  HH Pandya                48       890   596    34          57     61     18.541667
158  HM Amla                  8        426   286    7           47     16     53.250000
159  HV Patel                 12       115   90     9           6      7      9.583333
160  Harbhajan Singh          42       447   313    25          48     20     10.642857
161  Harmeet Singh            1        14    6      1           3      0      14.000000
162  Harpreet Brar            5        81    73     0           5      3      16.200000
163  Harpreet Singh           1        13    19     1           0      0      13.000000
164  I Malhotra               1        7     4      0           1      0      7.000000
165  I Sharma                 8        31    29     4           2      2      3.875000
166  I Udana                  3        14    8      2           1      1      4.666667
167  IK Pathan                43       562   502    26          45     13     13.069767
168  IR Jaggi                 5        68    83     4           6      0      13.600000
169  IS Sodhi                 2        7     18     2           0      0      3.500000
170  Imran Tahir              3        20    18     1           3      0      6.666667
171  Iqbal Abdulla            5        9     14     0           0      0      1.800000
172  Ishan Kishan             33       845   656    31          74     39     25.606061
173  J Arunkumar              1        1     3      1           0      0      1.000000
174  J Botha                  16       138   131    13          15     1      8.625000
175  J Suchith                3        10    8      0           0      0      3.333333
176  J Theron                 1        0     2      1           0      0      0.000000
177  J Yadav                  4        40    38     2           2      1      10.000000
178  JA Morkel                43       515   397    25          32     27     11.976744
179  JA Richardson            2        15    25     2           2      0      7.500000
180  JC Archer                9        80    54     5           4      6      8.888889
181  JC Buttler               25       724   540    23          76     28     28.960000
182  JD Ryder                 14       297   219    13          33     11     21.214286
183  JD Unadkat               8        37    36     5           3      1      4.625000
184  JDP Oram                 9        97    102    7           6      4      10.777778
185  JDS Neesham              3        14    24     3           1      0      4.666667
186  JE Taylor                1        1     2      0           0      0      1.000000
187  JEC Franklin             5        118   88     4           11     5      23.600000
188  JH Kallis                38       934   853    38          100    18     24.578947
189  JJ Bumrah                11       22    24     3           1      0      2.000000
190  JJ Roy                   9        143   140    8           19     2      15.888889
191  JL Denly                 1        0     1      1           0      0      0.000000
192  JL Pattinson             2        15    13     1           2      0      7.500000
193  JM Bairstow              10       332   248    10          25     16     33.200000
194  JO Holder                7        65    60     7           5      3      9.285714
195  JP Duminy                47       1342  1064   27          82     58     28.553191
196  JP Faulkner              21       225   193    15          11     11     10.714286
197  JPR Scantlebury-Searles  2        8     6      1           0      1      4.000000
198  JR Hopes                 7        154   125    8           22     1      22.000000
199  JR Philippe              4        78    77     3           9      1      19.500000
200  Jaskaran Singh           1        3     3      1           0      0      3.000000
201  Joginder Sharma          2        16    11     2           1      1      8.000000
202  K Goel                   8        121   117    7           10     7      15.125000
203  K Gowtham                8        50    37     7           2      4      6.250000
204  K Rabada                 7        39    42     4           2      1      5.571429
205  K Yadav                  1        0     4      0           0      0      0.000000
206  KA Jamieson              4        29    27     1           3      1      7.250000
207  KA Pollard               91       1819  1314   67          120    115    19.989011
208  KB Arun Karthik          3        24    27     1           3      0      8.000000
209  KC Cariappa              2        10    6      1           0      1      5.000000
210  KC Sangakkara            38       1088  902    39          132    16     28.631579
211  KD Karthik               96       2285  1774   88          215    74     23.802083
212  KH Pandya                43       655   497    29          55     28     15.232558
213  KJ Abbott                2        13    7      0           0      1      6.500000
214  KK Cooper                6        54    31     4           4      4      9.000000
215  KK Nair                  32       749   592    33          75     21     23.406250
216  KL Nagarkoti             4        15    22     2           1      0      3.750000
217  KL Rahul                 47       1509  1173   40          138    62     32.106383
218  KM Jadhav                40       608   460    26          48     25     15.200000
219  KMA Paul                 4        13    22     4           0      1      3.250000
220  KP Appanna               1        0     1      0           0      0      0.000000
221  KP Pietersen             14       361   272    12          41     10     25.785714
222  KS Bharat                3        57    60     3           3      2      19.000000
223  KS Williamson            33       1012  764    27          97     30     30.666667
224  KV Sharma                20       128   123    11          8      4      6.400000
225  KW Richardson            2        9     17     1           0      0      4.500000
226  Kamran Akmal             1        53    28     0           4      3      53.000000

In [24]:
ByInnings(df, 2)

               batsman  innings  runs  balls  dismissals  fours  sixes        RPI
0    A Ashish Reddy     10       114   81     8           10     5      11.400000
1    A Chopra           1        2     3      1           0      0      2.000000
2    A Choudhary        2        10    8      2           0      1      5.000000
3    A Flintoff         2        40    43     2           3      1      20.000000
4    A Kumble           10       24    33     1           2      0      2.400000
5    A Mishra           29       217   234    15          16     4      7.482759
6    A Mithun           4        26    21     4           3      1      6.500000
7    A Mukund           1        0     1      1           0      0      0.000000
8    A Nehra            8        35    44     3           3      1      4.375000
9    A Nortje           2        4     5      1           0      0      2.000000
10   A Singh            3        1     6      3           0      0      0.333333
11   A Symonds          17       352   309    14          28     10     20.705882
12   A Uniyal           1        0     1      1           0      0      0.000000
13   A Zampa            2        5     8      2           1      0      2.500000
14   AA Bilakhia        4        40    47     2           3      0      10.000000
15   AA Chavan          1        4     2      1           1      0      4.000000
16   AA Jhunjhunwala    8        75    84     6           3      4      9.375000
17   AA Noffke          1        9     12     1           1      0      9.000000
18   AB Agarkar         7        62    62     3           3      2      8.857143
19   AB Barath          3        42    43     2           5      1      14.000000
20   AB Dinda           9        19    28     5           2      0      2.111111
21   AB McDonald        4        49    46     2           1      1      12.250000
22   AB de Villiers     82       1999  1482   59          159    92     24.378049
23   AC Blizzard        5        77    61     5           12     2      15.400000
24   AC Gilchrist       39       1126  792    36          133    51     28.871795
25   AC Thomas          3        20    17     2           1      1      6.666667
26   AC Voges           2        43    44     3           3      0      21.500000
27   AD Hales           3        96    66     3           8      6      32.000000
28   AD Mascarenhas     6        35    32     6           2      1      5.833333
29   AD Mathews         16       314   274    14          14     13     19.625000
30   AD Nath            4        24    31     4           2      0      6.000000
31   AD Russell         35       783   489    30          61     61     22.371429
32   AF Milne           4        22    29     4           0      1      5.500000
33   AG Murtaza         2        8     9      1           1      0      4.000000
34   AG Paunikar        2        25    27     2           5      0      12.500000
35   AJ Finch           39       911   725    34          93     36     23.358974
36   AJ Turner          3        3     10     2           0      0      1.000000
37   AJ Tye             6        53    39     4           4      3      8.833333
38   AK Markram         4        77    61     3           4      4      19.250000
39   AL Menaria         8        151   130    7           7      9      18.875000
40   AM Nayar           27       315   280    20          28     8      11.666667
41   AM Rahane          70       1907  1661   60          197    34     27.242857
42   AN Ahmed           5        32    25     0           3      1      6.400000
43   AN Ghosh           1        0     1      1           0      0      0.000000
44   AP Dole            1        30    19     1           2      1      30.000000
45   AP Majumdar        3        57    57     3           6      0      19.000000
46   AP Tare            11       142   110    9           13     7      12.909091
47   AR Patel           35       472   384    28          30     23     13.485714
48   AS Joseph          1        15    13     0           2      0      15.000000
49   AS Rajpoot         4        19    25     2           1      1      4.750000
50   AS Raut            8        115   98     5           8      3      14.375000
51   AS Yadav           1        3     4      0           0      0      3.000000
52   AT Carey           1        4     7      1           0      0      4.000000
53   AT Rayudu          81       1999  1675   68          173    68     24.679012
54   AUK Pathan         4        37    19     3           5      2      9.250000
55   Abdul Samad        10       122   79     9           7      8      12.200000
56   Abdur Razzak       1        0     2      0           0      0      0.000000
57   Abhishek Sharma    9        90    74     8           6      3      10.000000
58   Anirudh Singh      2        23    26     2           2      0      11.500000
59   Ankit Sharma       5        29    21     3           1      2      5.800000
60   Anmolpreet Singh   1        16    14     1           2      1      16.000000
61   Anuj Rawat         1        0     1      1           0      0      0.000000
62   Anureet Singh      5        25    39     4           2      0      5.000000
63   Arshdeep Singh     1        0     3      1           0      0      0.000000
64   Avesh Khan         1        4     3      0           1      0      4.000000
65   Azhar Mahmood      9        152   131    8           16     4      16.888889
66   B Akhil            6        45    29     4           2      4      7.500000
67   B Chipli           8        122   116    7           12     3      15.250000
68   B Kumar            26       127   141    14          11     2      4.884615
69   B Laughlin         3        4     10     2           0      0      1.333333
70   B Lee              8        60    49     5           5      3      7.500000
71   B Stanlake         1        5     2      0           1      0      5.000000
72   B Sumanth          2        22    22     1           3      0      11.000000
73   BA Bhatt           1        0     5      0           0      0      0.000000
74   BA Stokes          23       584   412    21          57     22     25.391304
75   BAW Mendis         2        2     5      2           0      0      1.000000
76   BB McCullum        50       1199  939    48          130    49     23.980000
77   BB Samantray       2        15    14     1           2      0      7.500000
78   BB Sran            4        8     11     1           0      0      2.000000
79   BCJ Cutting        6        93    58     4           5      7      15.500000
80   BJ Hodge           31       746   585    22          66     26     24.064516
81   BJ Rohrer          5        102   76     4           9      4      20.400000
82   BMAJ Mendis        2        12    18     2           0      0      6.000000
83   BR Dunk            2        25    22     2           5      0      12.500000
84   Basil Thampi       2        11    13     0           1      0      5.500000
85   Bipul Sharma       8        119   74     4           8      6      14.875000
86   C Munro            4        59    56     3           5      3      14.750000
87   C Nanda            1        0     1      1           0      0      0.000000
88   C Sakariya         1        1     5      0           0      0      1.000000
89   C de Grandhomme    11       170   150    8           11     8      15.454545
90   CA Ingram          10       127   121    8           13     3      12.700000
91   CA Lynn            23       710   503    20          71     38     30.869565
92   CA Pujara          10       182   189    7           19     2      18.200000
93   CH Gayle           65       2092  1543   54          165    156    32.184615
94   CH Morris          26       335   213    12          17     23     12.884615
95   CJ Anderson        13       231   178    10          18     14     17.769231
96   CJ Ferguson        4        56    68     2           5      0      14.000000
97   CJ Jordan          3        21    18     2           2      0      7.000000
98   CK Kapugedera      1        8     9      1           0      0      8.000000
99   CK Langeveldt      2        8     9      2           0      1      4.000000
100  CL White           19       288   288    17          25     7      15.157895
101  CM Gautam          7        91    84     5           8      3      13.000000
102  CR Brathwaite      4        34    30     4           5      1      8.500000
103  CR Woakes          6        29    28     2           1      2      4.833333
104  CRD Fernando       2        4     3      1           0      0      2.000000
105  CV Varun           3        9     15     0           0      0      3.000000
106  D Padikkal         11       333   263    10          34     10     30.272727
107  D Salunkhe         2        7     4      1           1      0      3.500000
108  D Wiese            5        99    73     3           10     3      19.800000
109  DA Miller          41       1124  842    27          71     55     27.414634
110  DA Warner          75       2569  1878   62          259    92     34.253333
111  DAJ Bracewell      1        12    9      0           1      0      12.000000
112  DB Das             12       120   101    6           12     4      10.000000
113  DB Ravi Teja       10       148   141    10          12     5      14.800000
114  DE Bollinger       1        0     1      0           0      0      0.000000
115  DH Yagnik          5        32    38     3           4      0      6.400000
116  DJ Bravo           52       708   598    32          51     31     13.615385
117  DJ Harris          2        45    44     2           5      1      22.500000
118  DJ Hooda           27       331   295    20          19     10     12.259259
119  DJ Hussey          25       583   466    18          39     30     23.320000
120  DJ Jacobs          2        23    23     2           2      2      11.500000
121  DJ Thornely        1        1     6      0           0      0      1.000000
122  DJG Sammy          8        75    63     4           0      6      9.375000
123  DJM Short          2        48    31     2           3      4      24.000000
124  DL Chahar          9        77    52     6           2      6      8.555556
125  DL Vettori         9        62    59     3           6      2      6.888889
126  DM Bravo           1        6     5      0           1      0      6.000000
127  DNT Zoysa          1        10    7      0           1      0      10.000000
128  DP Nannes          2        4     13     1           0      0      2.000000
129  DP Vijaykumar      1        1     1      0           0      0      1.000000
130  DPMD Jayawardene   43       1042  860    33          117    21     24.232558
131  DR Sams            2        3     6      2           0      0      1.500000
132  DR Shorey          2        13    20     2           0      1      6.500000
133  DR Smith           42       1280  889    37          132    68     30.476190
134  DS Kulkarni        12       79    90     5           5      2      6.583333
135  DS Lehmann         1        17    17     1           3      0      17.000000
136  DT Christian       15       133   118    8           6      6      8.866667
137  DT Patil           1        9     12     1           0      0      9.000000
138  DW Steyn           16       76    94     11          5      1      4.750000
139  E Lewis            6        152   127    6           10     9      25.333333
140  EJG Morgan         35       673   581    28          57     27     19.228571
141  F Behardien        2        9     8      1           1      0      4.500000
142  F du Plessis       47       1491  1173   42          140    45     31.723404
143  FA Allen           1        0     1      0           0      0      0.000000
144  FY Fazal           4        22    36     3           2      0      5.500000
145  G Gambhir          89       2460  2116   76          296    25     27.640449
146  GB Hogg            4        22    22     2           1      0      5.500000
147  GC Smith           18       370   399    19          49     2      20.555556
148  GC Viljoen         1        0     1      1           0      0      0.000000
149  GD McGrath         2        4     5      1           1      0      2.000000
150  GD Phillips        2        22    20     1           1      2      11.000000
151  GH Vihari          12       179   200    11          14     1      14.916667
152  GHS Garton         1        2     3      0           0      0      2.000000
153  GJ Bailey          16       246   241    12          20     7      15.375000
154  GJ Maxwell         42       915   622    35          89     43     21.785714
155  Gurkeerat Singh    13       244   217    11          28     3      18.769231
156  H Das              1        2     5      1           0      0      2.000000
157  H Klaasen          4        28    29     3           2      0      7.000000
158  HH Gibbs           18       414   416    16          39     13     23.000000
159  HH Pandya          37       586   417    22          40     37     15.837838
160  HM Amla            8        151   132    6           13     5      18.875000
161  HV Patel           12       72    57     8           5      4      6.000000
162  Harbhajan Singh    46       386   323    31          31     22     8.391304
163  Harmeet Singh      3        4     6      1           0      0      1.333333
164  Harpreet Brar      1        3     2      0           0      0      3.000000
165  Harpreet Singh     2        7     7      1           0      0      3.500000
166  I Sharma           10       24    33     3           2      0      2.400000
167  I Udana            1        1     3      1           0      0      1.000000
168  IC Pandey          1        0     2      1           0      0      0.000000
169  IK Pathan          39       577   479    27          42     24     14.794872
170  IR Jaggi           2        8     17     1           0      0      4.000000
171  Imran Tahir        5        13    19     3           2      0      2.600000
172  Iqbal Abdulla      8        79    72     1           9      1      9.875000
173  Ishan Kishan       23       607   433    18          47     35     26.391304
174  J Arunkumar        2        22    21     2           5      0      11.000000
175  J Botha            12       271   233    9           24     4      22.583333
176  J Suchith          4        58    46     2           6      3      14.500000
177  J Syed Mohammad    5        29    27     2           4      0      5.800000
178  J Theron           3        10    11     1           1      0      3.333333
179  JA Morkel          24       459   314    15          29     28     19.125000
180  JC Archer          12       115   74     8           7      8      9.583333
181  JC Buttler         39       1244  817    32          118    62     31.897436
182  JD Ryder           15       307   247    16          36     8      20.466667
183  JD Unadkat         8        68    63     5           6      2      8.500000
184  JDP Oram           2        9     8      1           0      1      4.500000
185  JDS Neesham        5        47    42     4           2      2      9.400000
186  JE Taylor          1        2     2      0           0      0      2.000000
187  JEC Franklin       11       209   221    7           14     4      19.000000
188  JH Kallis          57       1493  1438   51          155    26     26.192982
189  JJ Bumrah          7        34    35     4           3      1      4.857143
190  JJ Roy             4        186   124    3           20     7      46.500000
191  JJ van der Wath    3        18    17     2           1      1      6.000000
192  JM Bairstow        18       706   507    17          74     30     39.222222
193  JM Kemp            2        26    25     2           1      1      13.000000
194  JO Holder          9        124   99     6           6      8      13.777778
195  JP Duminy          28       687   616    22          44     21     24.535714
196  JP Faulkner        24       302   212    12          25     12     12.583333
197  JR Hopes           12       263   189    9           27     10     21.916667
198  JR Philippe        1        0     3      1           0      0      0.000000
199  Jaskaran Singh     3        5     8      1           0      0      1.666667
200  Joginder Sharma    3        20    19     2           0      1      6.666667
201  K Goel             8        97    122    7           7      2      12.125000
202  K Gowtham          11       136   76     6           11     8      12.363636
203  K Rabada           9        99    99     6           9      3      11.000000
204  K Upadhyay         2        12    9      0           0      1      6.000000
205  KA Jamieson        3        36    28     2           2      2      12.000000
206  KA Pollard         66       1449  973    47          92     99     21.954545
207  KAJ Roach          1        10    9      1           1      0      10.000000
208  KB Arun Karthik    5        27    26     4           1      1      5.400000
209  KC Cariappa        3        14    15     2           0      1      4.666667
210  KC Sangakkara      30       599   522    30          63     11     19.966667
211  KD Karthik         95       1761  1421   74          184    38     18.536842
212  KH Pandya          26       488   356    19          50     18     18.769231
213  KJ Abbott          1        0     1      1           0      0      0.000000
214  KK Ahmed           3        1     5      3           0      0      0.333333
215  KK Cooper          6        62    39     5           5      4      10.333333
216  KK Nair            34       731   582    30          85     18     21.500000
217  KL Nagarkoti       3        7     12     2           0      0      2.333333
218  KL Rahul           38       1764  1282   31          144    72     46.421053
219  KM Jadhav          40       588   542    28          53     15     14.700000
220  KMA Paul           1        5     4      0           1      0      5.000000
221  KMDN Kulasekara    1        5     3      0           1      0      5.000000
222  KP Appanna         2        2     3      1           0      0      1.000000
223  KP Pietersen       22       640   486    17          50     30     29.090909
224  KS Bharat          3        134   101    2           7      6      44.666667
225  KS Williamson      29       873   705    20          69     26     30.103448
226  KV Sharma          14       189   162    10          10     10     13.500000
227  KW Richardson      2        27    22     2           2      1      13.500000
228  Kamran Akmal       5        75    50     4           9      5      15.000000
229  Kamran Khan        1        3     5      1           0      0      3.000000
230  Karanveer Singh    4        12    17     1           1      0      3.000000
231  Kartik Tyagi       2        4     6      1           0      0      2.000000
232  Kuldeep Yadav      5        29    42     2           3      0      5.800000
233  L Ablish           1        0     2      0           0      0      0.000000
234  L Balaji           5        16    21     3           1      1      3.200000
235  L Ronchi           2        13    13     0           1      1      6.500000
236  LA Carseldine      3        56    54     3           8      0      18.666667
237  LA Pomersbach      10       183   166    8           13     8      18.300000
238  LE Plunkett        1        0     1      1           0      0      0.000000
239  LH Ferguson        1        18    13     0           1      1      18.000000
240  LJ Wright          3        28    28     2           3      1      9.333333
241  LMP Simmons        11       416   327    9           42     17     37.818182
242  LPC Silva          1        17    15     1           3      0      17.000000
243  LR Shukla          13       137   149    12          11     3      10.538462

In [9]:
ing2_df = ByInnings(df, 2)

In [10]:
ing1_df = ing1_df[['batsman', 'RPI']].rename(columns = {'RPI':'ing1_RPI'})

In [11]:
ing2_df = ing2_df[['batsman', 'RPI']].rename(columns = {'RPI':'ing2_RPI'})

In [12]:
main = pd.merge(ing1_df, ing2_df, on = 'batsman')

In [13]:
main = pd.merge(df, mdf, on = 'matchId', how = 'left')

In [14]:
def balls_per_boundary(balls, boundary):
    if boundary > 0:
        return balls/boundary
    else:
        return balls/1
    
def balls_per_dismissal(balls, dismissal):
    if dismissal > 0:
        return balls/dismissal
    else:
        return balls/1

In [15]:
def ByCustom(df, current_venue, current_phase, current_opposition):
    
   
    df = df[df.venue == current_venue]
    df = df[df.phase == current_phase]
    df = df[df.bowling_team == current_opposition]

    df.reset_index(inplace = True, drop = True)


    df['IsDot'] = df['batsman_runs'].apply(lambda x : 1 if x == 0 else 0)
    df['IsOne'] = df['batsman_runs'].apply(lambda x : 1 if x == 1 else 0)
    df['IsTwo'] = df['batsman_runs'].apply(lambda x : 1 if x == 2 else 0)
    df['IsThree'] = df['batsman_runs'].apply(lambda x : 1 if x == 3 else 0)
    df['IsFour'] = df['batsman_runs'].apply(lambda x : 1 if x == 4 else 0)
    df['IsSix'] = df['batsman_runs'].apply(lambda x : 1 if x == 6 else 0)
   
    runs = pd.DataFrame(df.groupby(['batsman'])['batsman_runs'].sum()).reset_index().rename(columns = {'batsman_runs': 'runs'})
    balls = pd.DataFrame(df.groupby(['batsman'])['matchId'].count()).reset_index().rename(columns = {'matchId': 'balls'})
    innings = pd.DataFrame(df.groupby(['batsman'])['matchId'].apply(lambda x: len(list(np.unique(x))))).reset_index().rename(columns ={'matchId':'innings'})
    dismissals = pd.DataFrame(df.groupby(['batsman'])['player_dismissed'].count().reset_index().rename(columns = {'player_dismissed':'dismissals'}))
    sixes = pd.DataFrame(df.groupby(['batsman'])['IsSix'].sum().reset_index().rename(columns = {'IsSix':'sixes'}))
    fours = pd.DataFrame(df.groupby(['batsman'])['IsFour'].sum().reset_index().rename(columns = {'IsFour':'fours'}))
    dots = pd.DataFrame(df.groupby(['batsman'])['IsDot'].sum().reset_index().rename(columns = {'IsDot':'dots'}))
    
    df = pd.merge(innings, runs, on = 'batsman').merge(balls, on ='batsman').merge(dismissals, on ='batsman').merge(fours, on ='batsman').merge(sixes, on ='batsman').merge(dots, on = 'batsman')
    
    df['RPI'] = df.apply(lambda x: (x['runs']/x['innings']), axis = 1)
    df['SR'] = df.apply(lambda x: 100*(x['runs']/x['balls']), axis = 1)
    df['BPD'] = df.apply(lambda x: balls_per_dismissal(x['balls'], x['dismissals']), axis = 1)
    df['BPB'] = df.apply(lambda x: balls_per_boundary(x['balls'], (x['sixes'] + x['fours'])), axis = 1)
    df['dot_percentage'] = df.apply(lambda x: x['dots']/x['balls'], axis = 1)
    
    return df

In [16]:
def get_phase(over):
    if over < 6:
        return 'Powerplay'
    elif over < 15:
        return 'Middle'
    else:
        return 'Death'

In [17]:
main['phase'] = main['over'].apply(lambda x: get_phase(x))

In [18]:
mdf['venue'].unique()

array(['Rajiv Gandhi International Stadium, Uppal',
       'Maharashtra Cricket Association Stadium',
       'Saurashtra Cricket Association Stadium', 'Holkar Cricket Stadium',
       'M.Chinnaswamy Stadium', 'Wankhede Stadium', 'Eden Gardens',
       'M Chinnaswamy Stadium', 'Feroz Shah Kotla',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Green Park', 'Punjab Cricket Association IS Bindra Stadium',
       'Rajiv Gandhi International Stadium', 'MA Chidambaram Stadium',
       'Sawai Mansingh Stadium', 'Arun Jaitley Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Sheikh Zayed Stadium', 'Dubai International Cricket Stadium',
       'Sharjah Cricket Stadium',
       'MA Chidambaram Stadium, Chepauk, Chennai',
       'Wankhede Stadium, Mumbai', 'Narendra Modi Stadium, Ahmedabad',
       'Arun Jaitley Stadium, Delhi', 'Zayed Cricket Stadium, Abu Dhabi',
       'Brabourne Stadium, Mumbai', 'Dr DY Patil Sports Academy, Mumbai',
       'Maharashtra Cricket Association Stadium, Pune',
       'Eden Gardens, Kolkata',
       'Punjab Cricket Association Stadium, Mohali',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex'], dtype=object)

In [19]:
df1 = ByCustom(main, 'Wankhede Stadium', 'Middle', 'Chennai Super Kings')

In [20]:
df1 = df1[(df1.balls >= 20) & (df1.innings >= 1)]

In [21]:
df1.sort_values(by = 'RPI', ascending = False)

          batsman  innings  runs  balls  dismissals  fours  sixes  dots        RPI          SR   BPD        BPB  dot_percentage
32  V Sehwag       1        56    30     0           3      5      8     56.000000  186.666667  30.0  3.750000   0.266667
29  ST Jayasuriya  1        55    20     0           6      4      4     55.000000  275.000000  20.0  2.000000   0.200000
11  Ishan Kishan   1        33    24     1           4      1      9     33.000000  137.500000  24.0  4.800000   0.375000
31  V Kohli        1        29    21     0           3      0      4     29.000000  138.095238  21.0  7.000000   0.190476
17  LMP Simmons    2        50    49     2           3      2      23    25.000000  102.040816  24.5  9.800000   0.469388
13  KD Karthik     1        23    23     1           2      1      12    23.000000  100.000000  23.0  7.666667   0.521739
34  YK Pathan      2        45    44     1           5      1      22    22.500000  102.272727  44.0  7.333333   0.500000
27  SA Yadav       2        43    36     1           5      0      10    21.500000  119.444444  36.0  7.200000   0.277778
23  RG Sharma      7        146   114    2           12     4      29    20.857143  128.070175  57.0  7.125000   0.254386
12  KA Pollard     3        60    26     1           2      7      8     20.000000  230.769231  26.0  2.888889   0.307692
2   AT Rayudu      3        56    48     1           5      1      15    18.666667  116.666667  48.0  8.000000   0.312500
14  KH Pandya      2        34    28     0           4      1      13    17.000000  121.428571  28.0  5.600000   0.464286
25  RV Uthappa     1        16    22     0           2      0      13    16.000000  72.727273   22.0  11.000000  0.590909
28  SR Tendulkar   3        48    40     2           6      1      16    16.000000  120.000000  20.0  5.714286   0.400000